### ISSUE TITLE
site web et forum frontieres

### ISSUE THREAD

**Issue by ghost** [linuxmao-org/Frontieres#108]
Est ce que la communautée serait interessée à un site web et forum de discussion autour de frontieres? C'est un des seuls outils de granular synth sur linux et je pense que cela pourrait aider à la communeauté. J'offrirais le nom de domaines et l'hébergement  gratuitement si il y à un intéret.

**Comment by ghost** [comment]
Je vois qu'il y a beaucoup a faire avant de faire un site, comme la docu ou autre. Je vois ce que je peux faire pour aider. 

Est ce que de copier et traduire les information de borderland dans le readme pourrait etre un bon debut? Simplement pour aider les gens a commencer a utiliser l'outil?

**Comment by trebmuh** [comment]
@damarusama voir #71
