### ISSUE TITLE
Ajouter/supprimer des échantillons depuis l'IGU

### ISSUE THREAD

**Issue by trebmuh** [linuxmao-org/Frontieres#11]
Ça serait chouette de pouvoir ajouter/supprimer des échantillons depuis l'IGU.

Pour l'instant en cliquant-droit sur le rectangle d'un échantillon, on peut le sélectionner.

J'imagine un menu déroulant lors d'un clic droit sur un rectangle d'échantillon avec plusieurs options :

- copier
- supprimer
- choisir la taille de l'échantillon à utiliser (voir #15)

Et un menu déroulant avec un clic-droit sur un espace vide (pas sur un rectangle d'échantillon) avec plusieurs options :

- coller
- charger un son

**Comment by jpcima** [comment]
Aussi, je remarque que le logiciel ouvre un port d'entrée audio en Mono, et rien ne fait du son entrant.
Le logiciel n'est il pas prévu pour permettre l'enregistrement de son à la volée ?

**Comment by trebmuh** [comment]
Ah ? Tu es sur que c'est un port d'entrée audio ? Moi je n'en ai pas ici. En entrée, j'ai juste un port MIDI (que je n'ai pas essayé de faire fonctionner).

**ÉDITION :** ah si, en fait il y a bien un port audio en entrée. À en lire [la documentation](https://librazik.tuxfamily.org/doc2/logiciels/borderlands#generalites), il est censé pouvoir enregistrer le son d'un micro pour en faire un échantillon. Jamais testé. À voir si ça fonctionne.

**Comment by jpcima** [comment]
>ah si, en fait il y a bien un port audio en entrée. À en lire la documentation, il est censé pouvoir enregistrer le son d'un micro pour en faire un échantillon. Jamais testé. À voir si ça fonctionne.

les données entrantes ne sont pas utilisées ; quant au port MIDI, c'est moi qui l'ai rajouté mais il n'a aucune réaction au message entrant pour le moment, j'ai juste mis en place la base du traitement.

**Comment by trebmuh** [comment]
port audio en entrée : peut être que c'est une fonctionnalité qui n'a été mise en place que dans la version payante ?

port MIDI en entrée : merci pour les infos.

**Comment by olof29** [comment]
cette issue me semble maintenant resolue
