### ISSUE TITLE
Redimension des fenêtres des échantillons avec la souris

### ISSUE THREAD

**Issue by trebmuh** [linuxmao-org/Frontieres#12]
Ça serait chouette de pouvoir redimensionner les rectangles représentant les échantillons en cliquant avec la souris sur leurs coins (comme pour redimensionner une fenêtre dans un environnement de bureau quoi) en alternative à l'[utilisation des touches du clavier alpha-numérique](https://librazik.tuxfamily.org/doc2/logiciels/borderlands#les_controles).

**Comment by olof29** [comment]
chez moi, je n'ai jamais reussi d'ailleurs a redimensionner avec les touches du clavier...

**Comment by trebmuh** [comment]
@olof29 ici, ça fonctionne. Il faut préalablement sélectionner le rectange.

**Comment by olof29** [comment]
je suis de plus en plus interessé par cette fonctionnalité, car je viens de faire essayer Frontieres à un ami, dont le premier reflexe a été d'essayer de faire ça.
(chez moi, il est d'ailleurs toujours impossible de redimentionner les echantillons avec les touches clavier... quelle methode exactement utilisez vous ?)

**Comment by jpcima** [comment]
835c3ec9f5787629b1a5c181dfc519eef4ed0415

Je modifie la manière de redimensionner.
Suppression du redimensionnement par la touche `R`, qui fonctionne vraiment mal.

1. sélectionner un son
2. maintenir shift
3. redimensionner avec clic gauche + mouvent de la souris

**Comment by trebmuh** [comment]
Super !
Je ferme ici.
