### ISSUE TITLE
Inscription du nom de l'échantillon dans le rectangle de représentation

### ISSUE THREAD

**Issue by trebmuh** [linuxmao-org/Frontieres#14]
Une image plutôt qu'un long discours :

![borderlands-nomdesechantillons](https://user-images.githubusercontent.com/8705846/46315115-ce4db700-c5cc-11e8-8af7-6f642d7e2a1e.png)

**Comment by jpcima** [comment]
Ce que j'interpréte de la vision de cette image là, c'est que t'as vraiment des yeux de chat pour lire du noir sur fond de gris. ce qui ne manque pas de m'évoquer le thème de couleur du site lzk. :grin: 
(ou alors peut-être, c'est moi qui suis daltonien à mon insu :grin: )

**Comment by trebmuh** [comment]
C'est juste un brouillon rapide pour faire passer l'idée :wink:

**Comment by olof29** [comment]
je prefererais pour ma part pouvoir laisser le visuel "artistique".
je m'explique : j'utilse meme le visuel en projection lors de concerts. donc si on met les noms, il vaudrait mieux qu'au moins ce soit facultatif (type une touche clavier qui fait la balance ou une option à cocher) ou s' il s'affichait en bulle contextuel au survol du rectangle (facultatif aussi)

**Comment by trebmuh** [comment]
+1 pour une option facultative pour afficher les noms

**Comment by olof29** [comment]
j'ai realisé une fonction pour afficher le nom de l'echantillon  selectionné en appuyant sur la lettre "N"
elle affiche aussi le numero du cloud selectionné 
le tout en utilisant le mode d'affichage habituel des parametres des clouds
pull request déposé pour cela

**Comment by olof29** [comment]
est ce que la façon dont cette issue a été résolue convient ? peut on fermer cette issue ?

**Comment by trebmuh** [comment]
Salut @olof29 , je viens de tester, et merci pour ça, c'est déjà un premier pas.
Ceci dit, ça n'est pas ce que j'avais en tête, comme décrit dans l'image de départ. Pour l'instant, je peux seulement avoir le nom d'un des échantillons.

En tout cas, merci d'avoir fait un truc déjà !

**Comment by jpcima** [comment]
Implémenté : bc86f43d058f281e2e34029b9586ffe71865a7c0

**Comment by trebmuh** [comment]
Nickel, je ferme ici.
