### ISSUE TITLE
pouvoir mémoriser une configuration

### ISSUE THREAD

**Issue by olof29** [linuxmao-org/Frontieres#25]
pour que Frontieres soit un instrument complet, il faudrait, à mon avis, pouvoir mémoriser entièrement une configuration :
- les echantillons concernés
- la place des échantillons
- la taille, et l'orientation des echantillons
- la place des clouds
- les paramètres des clouds

ce n'est qu'ainsi qu'on peut etre à meme de reproduire une oeuvre musicale avec frontieres, sinon, on reste toujours dans le jet unique
cela aurait des consequences sur la question des repertoires utilisateur (il faudrait en fait laisser l'utilisateur mettre un projet musicalsous forme d'un repertoire ou il veut, et y mettre un fichier de configuration et les echantillons dans un sous repertoire loops)

**Comment by trebmuh** [comment]
Ça me semble une très bonne idée de pouvoir sauvegarder ça sous forme de "session Frontieres" dans un fichier.
:+1:

**Comment by olof29** [comment]
Bon, j'ai commencé ce travail.
- j'ai appelé scene un configuration.
- Je sais appeler une fonction de mémorisation depuis l'espace de travail (j'ai chosi la lettre "M" à cet effet).
- Je sais demander un nom de scene en affichant une fenetre de choix de fichier qui pointe vers le répertoire de travail ou sont les echantillons, ou vers le repertoire utilisateur, si es echantillons par defaut ont ete chargés. (avec demande de confirmation d'ecrasement si le fichier choisi existe deja)
- J'ai chois l'extension ".scn" pour les fichiers scene (mais c'est une constante qui peut donc etre différente si ça ne convient pas)
voici les infos que je prévois d'enregistrer dans ces scenes : 
- en premier, le chemin d'acces au repertoire de travail des echantillons.
- ensuite, les infos des echantillons : nom du fichier, orientation du rectangle, emplacement sur l'espace de travail  (x,y), et taille (x,y). pour l'instant, je ne sais pas comment recuperer ces informations dans ma fonction. (la seule chose que j'ai pour le moment, c'est le nombre d'echantillons)
- puis les infos sur les clouds. pour l'instant, je ne sais pas non plus comment acceder à ces infos dans ma fonction. (je sais comment acceder aux infos d'un cloud, mais ne sais pas comment trouver la liste des clouds existants)
Si vous avez des infos sur ces questions, je suis donc preneur.

**Comment by olof29** [comment]
avancement du travail 
j'ai pu gerer entièrement la sauvegarde de tous les paramètres d'une scene dans un fichier .scn comme decrit ci dessus.
il me reste maintenant à gérer la recharge d'une scene.
j'envisage pour cela de creer une fenetre de depart dans laquelles on pourra choisir entre creer une nouvelle scene, ce qui nous enverra sur la fenetre de choix du repertoire de travail, et charger une scene, qui nous enverra vers une fenetre de selection de fichiers .scn à partir du repertoire utilisateur.

**Comment by jpcima** [comment]
C'est intéressant comme idée, j'y suis entièrement favorable.
Ce qui m'a traversé l'esprit, c'est que l'emplacement des fichiers soit écrit en chemin relatif au `scn`, lorsque celui-ci se situe dans un sous-chemin du dossier de projet.
Ainsi le projet sera relocalisable et on pourra le transmettre d'un ordinateur à un autre.

>puis les infos sur les clouds. pour l'instant, je ne sais pas non plus comment acceder à ces infos dans ma fonction. (je sais comment acceder aux infos d'un cloud, mais ne sais pas comment trouver la liste des clouds existants)
Si vous avez des infos sur ces questions, je suis donc preneur.

L'essentiel des données internes du logiciels sont référencées par des variables globales.
Voir les fichiers `Frontieres.h/cpp` vers le début.

```
// grain cloud audio objects
vector<GrainCluster *> *grainCloud = NULL;
```

**Comment by olof29** [comment]
j'ai  en effet pensé au chemin en relatif, mais cela pose un probleme : si on deplace le ficher .scn, il devient inutilisable.
je vais reflechir plus avant à essayer de trouver une solution universelle, mais je ne suis pas sur que ce soit possible.
j'ai trouvé les variable concernées en global en effet, et je sais maintenant les utiliser.
là où je bute completement pour le moment, c'est dans la demarche pour pouvoir integrer une fenêtre "mainWindow" en amont du chargement actuel de Frontieres, dans laquelles on pourrait acceder par menus au chargement des scenes, ou au lancement d'une nouvelle session. Frontiere n'etant pas un projet Qt à la base, le compilateur n'a eu de cesse de m'insulter dans toutes mes tentatives.
je me suis donc resolu, pour le moment, à laisser de coté cette idée, et l'ai remplacée par une démarche malheureusement moins élégante .
avancement du travail : 
- Frontieres commence par afficher une boite message demandant si on veut charger une scene préenregistrée (deux boutons yes/no traductibes)
- si la réponse est non, Frontieres affiche la fenetre de demande du repertoire de travail
- si la réponse est oui, Frontieres affiche une fenêtre de recherche de fichiers .scn
- le fichier .scn est lu pour connaitre le repertoire de travail de la scene qui devient le repertoire de travail de Frontieres
- Frontieres continue son travail habituel de chargement des echantillons presents dans ce repertoire.
- le fichier scene continue d'etre lu pour replacer les echantillons
- un test est effectué sur les echantillons proposés dans le fichier scene. s'ils sont bien presents dans le repertoire de travail, ils sont redimentionnés et replacés selon la scene. s'ils n'y sont pas, un message traductible est affiché dans la console prevenant que cet echantillon de la scene n'a pas été trouvé, et on passe au suivant.
- si un echantillon présent dans le répertoire de travail ne figurait pas dans la scene chargée, il sera quand meme présent dans l'espace de travail (attention donc ensuite à le déplacer pour qu'il n'interfère pas avec la configuration sonore voulue
- je cherche une logique pour traiter ces echantillons "intelligemment", ne voulant pas les empecher d'etre là, mais voulant les empecher de changer le son... peut etre les déplacer en dehors de  la zone d'effet des clusters de la scene, mais ce sera pour plus tard, c'est assez compliqué. ça me semble pouvoir rentrer dans la même logique que la future fonctionnalité de rajout d'échantillons "à la volée".
- j'en suis au rechargement des clusters qui devront etre crées dans Frontieres, il me faut donc maintenant identifier la démarche dans Frontieres pour y parvenir.
- il me reste plusieurs interrogations à propos des rectangles de visualisation des echantillons.
je ne sais pas de quoi il en retourne exactement au sujet de la partie de l'echantillon qui est visualisée (voir l'issue "Choisir la longeur de l'échantillon dans l'IGU #15"), et je ne sais donc pas si ce qui a été mémorisé dans la session sera exactement identique, etant donné que Borderlands avait la facheuse tendance à insérer des fonctions alléatoires à plusieurs endroit du chargement des echantillons.
je ne sais toujours pas comment arriver à redimentionner un rectangle d'echantillon. je n'y arrive tout bonnement pas chez moi. alors soit je suis une quiche, soit les explications à ce sujet sont trop obscures, soit il y a un probleme lié au fait que je travaille exsclusivement sur un touchpad de portable.
je ne peux donc pas tester les fonctions de redimentionnement comme il faut avec les scenes.
si quelqu'un qui arrive à redimentionner peut me donner precisement la methode qu'il emploie, ça me permettra peut etre d'eviter de m'arracher les quelques cheveux qu'il me reste.

**Comment by jpcima** [comment]
@olof29

>là où je bute completement pour le moment, c'est dans la demarche pour pouvoir integrer une fenêtre "mainWindow" en amont du chargement actuel de Frontieres, dans laquelles on pourrait acceder par menus au chargement des scenes, ou au lancement d'une nouvelle session

Ce n'est pas nécessaire de créer une autre `mainWindow` car il en existe déjà une.
La `MyGLWindow` est une fenêtre principale.

`class MyGLWindow : public QMainWindow`

Seulement cette fenêtre principale n'est pas dotée de menus où quoi que ce soit d'autre, il faut le rajouter. Celle-ci contient uniquement la scène OpenGL.

`MyGLScreen *screen = new MyGLScreen;`
`setCentralWidget(screen);`

Une manière consiste à le faire en code directement. (cf. [QMainWindow::setMenuBar](https://doc.qt.io/qt-5/qmainwindow.html#setMenuBar))
L'autre manière c'est de refaire la MainWindow en Qt designer. Je peux te guider si tu as besoin.

> je vais reflechir plus avant à essayer de trouver une solution universelle, mais je ne suis pas sur que ce soit possible.

Il existe des programmes à ma connaissance qui sauvegardent l'équivalent du scn et fichiers annexes en dossier qui porte l'extension du format.
(exemple : Jalv et presets.lv2, les projets Ardour)

> je ne sais pas de quoi il en retourne exactement au sujet de la partie de l'echantillon qui est visualisée 

Je suis pas encore familiarisé avec cette partie, aussi je ne sais pas répondre immédiatement et avec certitude à cette question.
J'observe que `SoundRect` est doté des méthodes `move` et `setWidthHeight`.
Les `SoundRect` sont accessibles à partir de la donnée globale `soundViews`.

Si tu butes sur un long moment sur un problème lié à la compilation, poste ta branche quelque part et j'essayerai d'apporter mon aide du mieux que je peux.

**Comment by olof29** [comment]
avancement du travail 
- c'est ok, ça marche !
apres quelques prises de tete, ça finit par fonctionner. je peux donc enregistrer une scene, et au lancement du programme, il est possible de charger une scene enregistree.
- pour l'heure, je n'ai pas changé la façon de faire en rapport avec les repertoires, ça peut faire l'objet d'une prochaine issue.
- pour l'heure, je n'ai pas changé la façon de faire en rapport avec la mainWindow, cela releve d'une autre issue, à mon avis, qui sera centrée sur l'ergonomie.
- en matiere de traduction, j'ai pris le parti pris de permetttre la traduction des choses qui apparaissent à l'utilisateur, et pas de celles qui sont envoyées a la console. il n'est pas certain que la methode que j'ai utilisee pour cela soit la meme que celle actuelle. cela peut faire partie d'une autre issue centree sur la traduction.
- je propose donc un nouveau commit (qui peut remplacer le percedent au sujet du choix du repertoire utilisateur) pour ces nouvelles fonctionnalités.

**Comment by jpcima** [comment]
J'ai réalisé un travail important de restructuration depuis la PR précédente.
C'est un pas vers la réalisation d'une gestion de scènes un peu plus dynamique.

- J'ai adopté un format de fichier fomatté en json.
- J'ai ajouté quelques éléments d'interface graphique.
- J'ai découplé un certain nombre de composants et j'ai adapté la hiérarchie de fichiers en conséquence.

On peut désormais charger un fichier scène dans une structure, sans pour autant le rendre effectif immédiatement. Le moteur de synthèse fait également appel à une instance de `Scene` pour stocker son état courant : sons, nuages, visus.

Désormais, je souhaite retravailler le chargement des échantillons.
Il faut pouvoir charger des scènes qui travaillent avec différentes collections d'échantillons. J'ai réfléchi à un procédé comme ceci :
- la scène renseigne le nom d'échantillon (ex : `foo.wav`). Je vais chercher, dans l'ordre : les chemins audio renseignés dans le fichier scène, le chemin utilisateur, et enfin le chemin système.
- les dossiers des sons peuvent être indiqués en absolu, ou en relatif par rapport au fichier scène. 
- à la sauvegarde, on enregistrera des chemins audio en relatif s'ils appartiennent à un sous-chemin du dossier contenant le fichier de scène, en absolu sinon.
- au chargement, si 1 ou plusieurs fichiers son ne peuvent être trouvés, on fait apparaitre une boîte de dialogue qui nomme le premier fichier son manquant, et invite l'utilisateur à choisir un dossier où trouver celui-ci.

:warning: inconvénient de cette méthode : il faut veiller à ne pas utiliser deux fichiers homonymes dans des dossiers différents (ex : `foo/quux.wav` `bar/quux.wav`), car le programme ne saura alors charger que le premier des deux.

**Comment by jpcima** [comment]
J'ai implémenté la logique dont j'ai parlé au post précédent et j'ai testé la plupart des cas.
Désormais, les sons sont recherchés dans les chemins (dans cet ordre)
1. la propriété `audio-path` du fichier scène
2. le chemin utilisateur (~/.local/share)
3. le chemin système (<préfixe>/share)

**Comment by olof29** [comment]
dans l'issue  : les sauvegardes ne sont pas identiques à la scene sauvegardee à cause des grains qui changent #37
je fais etat de la difference entre les sons d'une scene et la recharge de sa sauvegarde. 
ceci est du au caractere aleatoire des grains.
je pense que cette remarque est plus a sa place ici que dans une nouvlle issue
c'est pourquoi je la remets ici , et ferme l'issue en question

> c'est particulierement remarquable sur des clouds rythmiques, a chaque recharge d'une sauvegarde, le rythme est different.
ceci est du au fait que les grains sont crees avec une part d'alleatoire.
si on veut vraiment avoir l'identique, on n'y coupera pas de devoir aussi sauver les grains.
ce qui nous amenera sans doute à vouloir vraiment controler les grains aussi

**Comment by olof29** [comment]
fonctionnalité implantée
