### ISSUE TITLE
Faire passer Frontieres en version entièrement Qt

### ISSUE THREAD

**Issue by olof29** [linuxmao-org/Frontieres#27]
pour pouvoir gérer simplement l'interface utilisateur des sessions Frontières, mais aussi donner des alternatives à la gestion des paramêtres des clouds, et pouvoir proposer un paramétrage midi, ne serait il pas préférable de faire passer intégralement le projet sous Qt creator ?
J'ai pour ma part réussi à charger le projet Frontieres dans Qt creator en chargeant le fichier cmake.txt dans celui ci, mais la forme du projet n'est pas celle d'un projet typique de Qt creator avec widgets.
Mes tentatives pour incorporer Frontieres dans un nouveau projet Qt creator avec Widgets se sont pour le moment soldées par des erreurs de compilations, dont la plupart sont simplement des erreurs liées à des chemins d'accès à certains entetes qui sont dans le sous repertoire librairies, mais d'autres me laissent pour le moment sans réponses.

**Comment by jpcima** [comment]
J'essaye de mon côté et j'écris un projet Qmake.

**Comment by jpcima** [comment]
J'ai mis un fichier de projet pour Qt. (le fichier .pro)
Il se construit correctement chez moi, seules les traductions n'y sont pas intégrées.
Système de traduction à revoir et simplifier si possible

**Comment by olof29** [comment]
il me semble que cette issue peut etre considérée comme résolue, depuis l'utilisation des interfaces visuelle dans Qt et de la traduction
