### ISSUE TITLE
Problème de logique au chargement d'une scene

### ISSUE THREAD

**Issue by olof29** [linuxmao-org/Frontieres#31]
superbe boulot que la mouture "propre" de la gestion des scenes.
il subsite neanmoins un problème qui n'exisatait pas dans la mouture non afinée  : 
- si on choisit de charger une scene au lancement, on ne devrait pas ensuite passer par la fenetre de demande du repertoire de travail, c'est le repertoire de la scene qui doit etre pris en compte.
- là on passe par la fenetre de choix de la fenetre de travail, et en plus elle est branchée par defaut sur le repertoire par defaut et non sur celui de la scene. du coup si on valide, on a une scene vide de tout echantillon (ce qui n'est pas non plus normal)

**Comment by jpcima** [comment]
Je n'ai pas réussi à reproduire ce problème (ou pas bien compris).
En tout cas cette implémentation est incomplète et je compte continuer à l'améliorer, en réalisant une approche plus souple du chargement d'échantillon.

**Comment by olof29** [comment]
j'explique alors 
dans ce que j'avais ecrit, je testais apres la demande initiale pour choisir entre charger une scene ou en creer une nouvelle, si on avait choisi d'en charger une, et qu'on avit choisi laquelle, je ne demandais pas ensuite sur quel repertoire de travail se mettre, puisque celui de la scene allait etre utilisé.
maintenant, si je demande de charger une scene, que je la choisis, le programme me demande quand meme ou est mon repertoire de travail, ce qui m'oblige a refaire le chemin et a me mettre sur le meme repertoire moi meme alors qu'il le sait deja. c'est une perte de temps. et en plus, si je choisi un autre repertoire que celui de la scene, eh bien le programme ne charge aucun echantillon

**Comment by olof29** [comment]
le probleme est en fait à la sauvegarde : la scene a enregistre "audio-path": "",
donc un repertoire de travail vide, alors qu'elle aurait du mettre le repertoire de travail.

**Comment by olof29** [comment]
reparé en initialisant m_audioPath, je fais un pull request à ce sujet

**Comment by trebmuh** [comment]
@olof29 c'est quel PR ?

**Comment by olof29** [comment]
le probleme est resolu
