### ISSUE TITLE
normalisation des noms d'entités

### ISSUE THREAD

**Issue by olof29** [linuxmao-org/Frontieres#33]
ce travail a ete deja commencé avec l'entrée en jeu de l'entité scène. il merite d'etre approfondi.
par exemple, la meme entité est parfois appelée cluster, parfois cloud, une autre parfois voice, parfois grain, une autre parfois sound, parfois audiofile, parfois sample.
il y a aussi une visualisation appelee Rect, et l'autre Vis, il ya cloud et cloudVis, ne faudrait il pas l'equivalent pour les sons (sound et soundVis, ou audiofile et audiofileVis) ?
normailser tout cela clarifierait bien le code

de plus, quels sont les regles pour les noms de classes, variables globales, locales, constantes, enums, etc ? (certains enums sont tout en majuscules, d'autres non)

**Comment by jpcima** [comment]
Même observation, je suis entièrement d'accord.

**Comment by olof29** [comment]
c'est fait pour les clouds.
- cluster, graincluster, graincloud sont devenus cloud
- grainclustervis est devenu cloudvis

par contre, j'ai un serieux probleme avec la notion de son.
on trouve sound, sample, wave, soundfile, audiofile, et remplacer par un d'entre eux met un bazard pas possible parceque ce sont parfois les memes entités, parfois des entités differentes.
j'aurais volontier utilisé sample qui me semble etre le plus parlant, mais les utilisations actuelles de ce terme m'amenent à m'interroger : on trouve un SAMPLE (en majuscules) deja dans theglobals.h, qui semble lié à l'utilisation de rtAudio, est ce un terme reservé pour rtAudio ?
je ne comprends pas bien non plus ce que la notion de frame represente.
bref, certaines notions, dans les profondeurs de Frontieres me manquent pour pouvoir aller plus loin pour le moment.
peut etre qu'une representation graphique de toute la structure de données serait un bon outil

**Comment by jpcima** [comment]
>on trouve un SAMPLE (en majuscules) deja dans theglobals.h, qui semble lié à l'utilisation de rtAudio, est ce un terme reservé pour rtAudio ?

Non, `SAMPLE` est une définition propre à l'application, son rôle est de permettre une compilation soit en flottant de simple ou double précision. Je vois qu'il est assez peu répandu dans le code source.

Une chose à noter c'est que si on passe `SAMPLE` en simple précision, alors l'espace occupé en mémoire par les fichiers son sera 2 fois moindre.

Disons qu'en programmation audio conventionnelle, on utilise plutôt le `float` par règle et le `double` par exception, dans les cas où c'est véritablement important.
Je n'ai rien recontré dans Frontières qui me justifie, a priori, la nécessité de l'emploi de la précision double.

>je ne comprends pas bien non plus ce que la notion de frame represente.

Un échantillon c'est une valeur de signal prise à un instant `t`. Une trame c'est un regroupement d'échantillons qui viennent de plusieurs signaux (dans le cas de stéréo, 2 échantillons).
Une valeur en trames correspond au nombre d'itérations que fait le traitement audio.

>sound, sample, wave, soundfile, audiofile

Selon moi il faut que soient distingués 2 choses : le fichier son et son contenu d'une part, d'autre part ses instanciations dans la scène (les `SoundRect`).

**Comment by olof29** [comment]
> Selon moi il faut que soient distingués 2 choses : le fichier son et son contenu d'une part, d'autre part ses instanciations dans la scène (les `SoundRect`).

cela ne pourrait il pas correspondre à la même logique que pour les clouds et les grains, à savoir Sample et SampleVis ?

**Comment by olof29** [comment]
fait pour les fichiers son
- AudioFile est devenu Sample
- AudioFileSet est devenu SampleSet
- SoundRect est devenu SampleVis

il reste quelques variables par ci par là encore à traquer pour éliminer les termes wave, sound...

**Comment by olof29** [comment]
- sound transformé en sample
il reste quelques variables par ci par là encore à traquer

**Comment by olof29** [comment]
globalement plus clair maintenant, en general, on peut considerr que c'est fait
