### ISSUE TITLE
probleme à la recharge d'une scene sur l'orientation visuelle des echantillons

### ISSUE THREAD

**Issue by olof29** [linuxmao-org/Frontieres#34]
ils sont tous mis à la verticale à la recharge.
j'ai verifié dans les fichiers de sauvegarde, il n'y pas de probleme, l'orientation est bien enregistree comme il faut, c'est à la recharge que le probleme se passe, j'ai regardé, mais n'ai pas ete en mesure d'en trouver la raison.

**Comment by jpcima** [comment]
Potentiellement corrigé dans a6a130f28c182b21e45ef9b8e78c09b2284a0445, ce qui enregistre l'orientation en type entier au lieu de chaîne. C'est un oubli de ma part alors que j'ai traduit le code `QTextStream` en `Json`.
Afin de corriger les fichiers scène qui existent il faudra retirer les guillemets autour de la valeur.

**Comment by olof29** [comment]
bien vu
pour les scenes , pas de souci pour moi, pour le moment, je ne fais pas encore de vrai projet musical avec frontieres, juste des tests

**Comment by olof29** [comment]
pour moi, ce probleme est résolu
