### ISSUE TITLE
la nouvelle logique de repertoire de travail pose plusieurs problemes

### ISSUE THREAD

**Issue by olof29** [linuxmao-org/Frontieres#35]
superbes fonctions que celles qui permettent de charger et enlever des echantillons à la volée.
mais du coup, la logique de travail en rapport avec le repertoire de travail se retrouve avec plusieurs lourdeurs
- on ne peut plus chosir son repertoire de travail au depart. cela amene à avoir systematiquement le repertoire par defaut des echantillons chargé. meme s'il n'y a que 4 echantillons dedans, ça va vite devenir gavant de devoir a chaque fois les supprimer, car il serait bien etonnant que l'on en veuille dans toutes nos scenes.
- on ne peut charger à la volée qu'un echantillon a la fois, donc vu que l'on ne peut plus choisir son repertoire de travail de base, si on veut charger les 120 echantillons qui sont dans un repertoire donné, par exemple, ça va prendre 120 manips...

je pense que la fonction de chargement a la volée, si elle permettait des selections multiples, resoudrait quasiment tout ça, pour peu qu'on ne mette plus de repertoire de travail par defaut du tout, qu'on laisse une scene vide au depart. 

la fenetre de depart demandant si on veut charger une scene ou en creer une nouvelle n'a plus non plus de sens

il va aussi devenir tres vite important de pouvoir afficher le nom des echantillons etant donné les origines multiples de ceux ci, sous peine de se perdre

**Comment by trebmuh** [comment]
> on laisse une scene vide au depart.

Si on part la dessus alors on peut imaginer une scene de "demo" qui utilise les 4 échantillons de base et qui soit accessible par le menu. Pour que les tout-nouveaux débutants puissent faire joujou rapidement. (_Hydrogen fait ça._)

> il va aussi devenir tres vite important de pouvoir afficher le nom des echantillons etant donné les origines multiples de ceux ci, sous peine de se perdre

Voir : https://github.com/linuxmao-org/Frontieres/issues/14

**Comment by jpcima** [comment]
>on ne peut plus chosir son repertoire de travail au depart. cela amene à avoir systematiquement le repertoire par defaut des echantillons chargé. meme s'il n'y a que 4 echantillons dedans, ça va vite devenir gavant de devoir a chaque fois les supprimer, car il serait bien etonnant que l'on en veuille dans toutes nos scenes.

Tu peux démarrer avec la scène vide si tu fermes la boite de dialogue, par la barre de titre ou par la touche échap. Je veux bien qu'on ajoute un 3ème bouton afin de réaliser le même effet.
J'ai essayé de faire disparaître la notion même de *répertoire de travail*.

>la fenetre de depart demandant si on veut charger une scene ou en creer une nouvelle n'a plus non plus de sens

À vrai dire, il est vrai que cette fenêtre d'accueil n'est plus forcément nécessaire désormais.

>on ne peut charger à la volée qu'un echantillon a la fois, donc vu que l'on ne peut plus choisir son repertoire de travail de base, si on veut charger les 120 echantillons qui sont dans un repertoire donné, par exemple, ça va prendre 120 manips...

Tu as raison, par ailleur c'est effectivement plus efficace de charger par lots, car ce n'est pas nécessaire alors de réinitialiser l'état interne des nuages 120 fois s'il y a 120 échantillons.

**Comment by olof29** [comment]
je trouve bonne l'idee d'olinuxx, fournir un, voir plusieurs scenes de demo est une bonne alternative.

pour les selections multiples d'echantillons, je ne sais pas si la fenetre de selection permet cela ?
si oui, ça n'est en effet peut etre pas beaucoup de changements... je ne sais pas, je suis assez lent a me familiariser avec le code

**Comment by olof29** [comment]
j'ai mis un pull request pour la selection multiple d'echantillons. ça fonctionne bien, et ça allege grandement le travail de l'utilisateur, en effet.

**Comment by olof29** [comment]
pour moi, le probleme soulevé dans cette issue est du coup résolu, à part la scene de démo.
