### ISSUE TITLE
Ergonomie du logiciel

### ISSUE THREAD

**Issue by jpcima** [linuxmao-org/Frontieres#4]
@trebmuh  À détailler.

> développer une méthode d'utilisation permettant de se rapprocher de l'ergonomie de ce logiciel sur une tablette, car pour l'instant, l'utilisation des touches de clavier n'est pas des plus faciles pour le logiciel, surtout quand on voit comment ce logiciel est utilisé sur iPad.

**Comment by trebmuh** [comment]
Voir [les vidéos de la version iPad](https://vimeo.com/fbkfbk).

**Comment by jpcima** [comment]
Je veux bien, mais l'idée de transformer la version libre en la version iPad, ça ne peut faire l'objet d'une seule tâche à soi tout seul.

Au moins, ce serait bien de lister les choses à faires et leur associer une priorité.
Également je pourrais trier les tâches à faire par leur difficulté de réalisation, afin didentifier ce qui peut être fait à plus ou moins court terme.
Perso j;aurais du mal à tout deviner.

(q: l'ami olof travaille-t-il sur d'autres développements sur le logiciel actuellement ?)

**Comment by trebmuh** [comment]
Exact, ça semble être un gros boulot.
J'ai mis un lien vers les vidéos à titre informatif pour pouvoir voir ce qu'il est possible d'en faire, à des fins de réflexion.

Je propose qu'on voit ça au fur et à mesure, après avoir vérifié et intégré les premières modifications de code en train d'être faites.

(r: je ne sais pas, espérons qu'il vienne nous rejoindre sur ce dépôt)

**Comment by olof29** [comment]
Serait il possible de faire disparaitre la barre de menu de la fenêtre principale lorsqu'on passe en mode plein ecran (touche "O") ?

**Comment by jpcima** [comment]
Oui c'est assez trivial à faire, j'ai mis un correctif à l'instant.
