### ISSUE TITLE
fenetre regroupant tous les parametres d'un cloud

### ISSUE THREAD

**Issue by olof29** [linuxmao-org/Frontieres#52]
je suis en train de commencer à créer une fenêtre éditable regourpant tous les parametres d'un cloud.
je m'interroge sur la bonne façon de l'intégrer à frontières : 
- est-ce que je la rends dépendante du cloud, auquel cas chaque cloud peut avoir sa fenetre.
avantage, on peut modifier les parametres d'un cloud même s'il n'est pas sélectionné dans la fenêtre principale.
inconvéniant, tout ça finira par être susceptible de prendre beaucoup de place mémoire, non ?
- est ce que je la rends unique, et son contenu change selon le cloud sélectionné ?
avantage, cela prend moins de place mémoire
inconvéniant, je ne sais pas trop à quel niveau du programme la creer (je pense qu'au niveau de MyGlWindow pourrait etre logique, mais n'en suis pas sur)

**Comment by jpcima** [comment]
Sans prétendre qu'une solution est nécessairement meilleure qu'une autre, pour ma part : ni l'une ni l'autre, j'instancierais la fenêtre à la demande. Création à l'ouverture de fenêtre, destruction à la fermeture.

**Comment by olof29** [comment]
oui, ça je pense savoir comment le faire (encore que je n'en sois pas certain, selon le focus modal ou non et le parent, ça peut varier, la destruction, me semble t'il), mais ça ne repond pas vraiment à la question de logique générale : je permets d'en créer un seule ou plusieurs ? je ne maitrise pas vraiment ce que ça peut representer en terme de memoire, et donc de performances

**Comment by jpcima** [comment]
Plusieurs, mais sous la contrainte d'1 fenêtre max pour un nuage donné.
A mon avis ce n'est pas nécessaire qu'elles soient modales.

Concernant la gestion mémoire, je pense que tu peux détruire la boite de dialogue lorsque l'utilisateur ferme celui-ci par le bouton :negative_squared_cross_mark:.
Au moment ou tu attrapes cet événement, il doit y avoir la possibilité d'invoquer `deleteLater()` sur l'instance de fenêtre.

**Comment by olof29** [comment]
maintenant, la question du bornage des parametres : 
beaucoup de parametresde clouds  dans frontieres semblent pouvoir varier à l'infini.
cela pose un petit probleme dans la saisie de ces parametres, les widgets demandant des limites d'encadrement de saisie. (je presume que cela posera aussi un probleme dans l'utilisation avec OSC)
ne devrait on pas définir des valeurs d'encadrement raisonnables ? 
exemple : mettre une durée des grains à 3 heures semble absolument inutile, ou un nombre de grains à 10 000 impossible à soutenir sans voir défiler les xruns, varier la tonalité au dela du spectre audible humainement n'a non plus aucun interet...

**Comment by olof29** [comment]
voici les parametres concernés : 
- tonalité : de 0,0001 à l'infini , vleur de base 1
- durée des grains : de 1ms à l'infini
- quantité de lfo : de 0 à l'infini
- fréquence de lfo : de 0 à l'infini
- nombre de grains : de 0 à l'infini

**Comment by jpcima** [comment]
Il serait bon, effectivement, de borner les paramètres.
Pour les durées cela dépend du besoin ; si celles-ci peuvent monter jusqu'à des valeurs importantes, alors il serait approprié de les manipuler en échelle logarithmique.
(par rapport aux valeurs de contrôle MIDI, ou aux cas où l'interface graphique les représenterait par un bouton rotatif ou fader)

**Comment by olof29** [comment]
j'ai mis un commit avec des bornes défibies dans la fenetre ele meme, mais il n'y a pas de bornes dans la saisie "traditionnelle" dans la scene. 
je songe à gérer ces limites  à partir d'un fichier, de manière à pouvoir les modifier sans devoir revenir sur le code lui même.
mais déjà, il faut voir si la fonction fenetre est satisfaisante, je verrai ces questions de limites dans un autre commit, je pense

**Comment by olof29** [comment]
le déplacement de clouddialog dans la partie interface a induit un souci au niveau de la mise à jour des valeurs, qui apparait chez moi dans une situation particuliere : 
- j'accorde mes clouds sur une note donnée d'oreille en manipulant le pitch depuis la fenetre clouddialog
- pour ça, je joue sur un clavier midi relié par jack à frontieres
- j'entends le son de mon clavier et celui du cloud
- petit à petit je change le pitch du cloud et l'accorde ainsi comme j'accorde une guitare d'oreille
- pour cela , je me sers de la zone de clouddialog ou on peut saisir le pitch manuellement, mais en l'editant avec les touches page up, pagedown qui permettent de modifier le pitch par pas de 0,10, puis j'affine avec les fleches hautes et basses qui permettent un pas de 0,001.
- lors de l'utilisation du pas de 0.10 par page up page down en repetant tres rapidement et la frappe clavier et simultanement l'appui sur le clavier ordi, la zone change de valeur de 0,10 mais souvent ensuite rechange seule de valeur de 0,001 dans le sens inverse.
- comme les bonnes valeurs d'accord sont tres souvent des valeurs rondes de pas de 0,10, cela est tres genant, car ça demande de repasser au pas de 0,001 qui est eloigné sur mon clavier ordi, je ne peux donc pas le faire à l'aveugle

je précise que je m'etais deja servi ainsi de frontieres avant le deplacement de cloudialog, et que ce probleme n'existait pas alors

**Comment by olof29** [comment]
- je ne peux plus non plus changer la zone midi note, elle revient toute seule à sa valeur de départ après changement : 
je veux y taper directement la valeur de la note (96 en l'occurence, à la place de 21, et ça me met 22 ou 24 ou ça revient à 21)
- idem pour le canal midi

**Comment by olof29** [comment]
tout cela est généré par la mise à jour dans un timer. je ne comprends vraiment pas cette méthode :

-  visiblement ça induit de sérieux problemes dans la saisie des valeurs

- ça déclenche des mises à jour à intervalles réguliers, qu'il y ait eu modifications ou pas ?
    si oui, ça mange forcement du temps de calcul inutilement.

- pour moi, gerer la mise à jour de la fenetre dans un timer n'est pas bon.
- si tu veux absolument demenager le declenchement de la mise à jour, il faut qu'elle soit déclenchée aux appels des fonctions de cloud qui font les set..parametre du cloud.

- si on ne le fait pas dans la fonction, il faut donc le faire juste apres chacun des appels à celle ci...

- je ne vois donc aucun intéret à l'avoir deplacé... à part le fait que maintenant le cloud n'a plus acces à la fenetre lui correspondant.

- je ne saisis toujours pas pourquoi il faut absolument decoupler le visuel du modele : 
en terme de logique de programmation, j'ai toujours appris à raisonner selon la méthode qui consite à se demander "qui appartient à qui", ou qui "dépend de qui", or clairement la fenetre des parametres d'un cloud dépend du cloud, puisqu'on a permis d'en avoir plusieurs, une par cloud.
- si au depart, à ma question : "en faut il une seule ou plusieurs ?", on avait répondu "une seule", là j'aurais compris cette logique de dire que la fenetre ne dépend pas du cloud, seul le contenu dépend de lui, mais ici c'est clairement le cas.

- tu dis que cela peut poser des problemes si modele et visuels sont liés. je ne comprends pas quel probleme cela poserait. est ce parcequ'une mise à jour en continu venant de l'exterieur comme un changement de volume en continu envoyé par le controle OSC, par exemple, declencherait trop de mises à jour visuelles, et risquerait de generer des xruns ? dans ce cas, ne pourrait on pas l'eviter en faisant simplement des mises à jour plus ciblées ? (là la mise a jour concerne toute la fenetre, on peut tres bien envisager de ne mettre à jour que les controles concernés, par exemple)

**Comment by jpcima** [comment]
>visiblement ça induit de sérieux problemes dans la saisie des valeurs

Oui, je peux effectivement reproduire ce problème.
Faut que j'étudie ce qui se passe précisément.

>ça déclenche des mises à jour à intervalles réguliers, qu'il y ait eu modifications ou pas ?
si oui, ça mange forcement du temps de calcul inutilement.

C'est la manière simple, et son impact en performance est très faible. En comparaison, le timer openGL invoque en permanence la boucle d'évément à taux de rafraichissement 50 trames/s.
Quoi qu'il en soit, cela n'est nullement gênant en MAO puisque le fil audio préempte l'interface graphique en toute circonstance.

>pour moi, gerer la mise à jour de la fenetre dans un timer n'est pas bon.

Je ne prétends pas qu'on ne peut pas faire mieux.
Par contre j'affirme que c'est possible passer un temps fou à affiner les méthodes de communication audio←→interface, pour davantage de complexité et très peu de gain.
Ceci est une solution simple, d'usage répandu, elle n'encombre pas le traitement audio de notification/fanion ou que sais-je, et cela me convient.

>je ne saisis toujours pas pourquoi il faut absolument decoupler le visuel du modele :

C'est une séparation de préoccupation. C'est particulièrement inquiétant de se retrouver dans une situation ou les éléments sonores se retrouvent en mélimélo avec des appels d'interface graphique ex: `updateDialog`. (j'ai eu notamment de "bons souvenirs" avec ça, avec un greffon audio dont j'ai repris la maintenance il y a pas si longtemps)

Le fait est que pour une fonction aussi innocente que changer le volume, le jour ou tu veux appeler ça depuis MIDI ou OSC, pour peu que ça soit mêlé à de l'interface graphique, tu ne peux plus...
Et cela n'est nullement mis en évidence par le moindre nommage ni commentaire, ce qui induit doublement à l'erreur.

>tu dis que cela peut poser des problemes si modele et visuels sont liés. je ne comprends pas quel probleme cela poserait.

Tu ne peux pas appeler l'interface graphique à partir d'un fil autre que celui ou l'interface graphique est instanciée. Il faut passer nécessairement par une méthode de communication annexe qui est compatible avec le TR.

**Comment by olof29** [comment]
ce qui se passe précisément est ceci : 
- on rentre dans une zone de saisie
- on commence à modifier son contenu
- on reçoit par le timer l'ordre de mise à jour
- la zone est mise à jour avant qu'on ait fini la saisie

j'ai fait quelques tests sur la longueur du delai du timer : 
- plus le temps du timer est important, plus les problemes sont rares, sans pour autant disparaitre.
- à certaines valeurs, comme celle de 500 ms, on n'a carrément pas le temps de saisir ne serait ce qu'un chiffre et de valider. donc il devient impossible de saisir quoique ce soit dans la zone, comme c'est le cas de la zone midi note par exemple.
- mais au dela de ces 500 ms, la mise à jour est trop lente quand on modifie les parametres depuis la fenetre openGL pour que les choses soient confortables en utilisation musicale (Frontieres est vraiment un instrument de musique en soit, et à ce titre doit non seulement veiller à offrir des capacités sonores interessantes, mais une interface utilisateur qui répond bien, et informe bien le musicien)

donc, selon moi, on peut améliorer les choses : 
- une premiere solution serait,  si on peut avoir un signal d'entree dans la zone, type "on_edit", de suspendre la mise à jour de la zone tant qu'on est en édition.
- mais dans ce cas, si on reste dans la zone sans jamais valider, plus aucune mise à jour ne sera faite.
(ceci dit ce n'est qu'un souci visuel sans consequence sur le son, mais si entre temps un autre moyen comme OSC a modifié la valeur du parametre, on aura une différence entre la valeur vue et la valeur entendue tant qu'on n'aura pas perdu le focus sur cette zone
- le widget n'a pas actuellement les évènements voulus pour faire ça, apparemment. donc il va etre nécessaire d'en dériver une version maison.


-  une deuxieme solution pourrait etre une mise à jour plus sélective, ne concernant que les parametres qui ont changé. peut etre en instanciant un drapeu de modif dans le cloud pour chaque parametre, qui serait testé dans le timer, ce qui empecherait la mise à jour de la zone si le parametre n'a pas ete modifié entre temps, et résoudrait donc le probleme de mise à jour avant la fin de la saisie.

mais, pour revenir sur la logique de programmation, la séparation du modèle, j'ai bien compris doit comme règle de base, être maintenue par rapport à l'interface de saisie, mais ne devrait elle pas aussi etre faite pour la restitution visuelle ? CloudVis reste lié à Cloud à l'intérieur de Cloud, cela ne devrait il pas alors aussi être évité ?

**Comment by olof29** [comment]
j'ai pu resoudre un bon nombre des soucis ci dessus grace à des drapeux de mise a jour dans cloud, et en passant la propriete keyboardtracking des doublespinbox a false
mais il rest sur le doublespinbox du pitch uniquement, le souci de microchangements à l'appui en continu sur la touche page up ou page down
j'ai le sentiment que ce souci n'a rien a voir avec les autres, mais qu'il serait lié à la conversion frequence/demi tons...
je mets un nouveau pr a ce sujet
