### ISSUE TITLE
retour d'expérience d'utilisation de frontieres

### ISSUE THREAD

**Issue by olof29** [linuxmao-org/Frontieres#57]
je mets ici un lien vers linuxmao pour le retour d'experience d'utilisation de frontières en cession de composition MAO avec une trentaines de gamins : 
[https://linuxmao.org/tiki-view_forum_thread.php?comments_parentId=89523&forumId=27](https://linuxmao.org/tiki-view_forum_thread.php?comments_parentId=89523&forumId=27)

et j'en profite pour ajouter quelques commentaires de debuggage : 
- [x] la sauvegarde des clouds ne sauve pas l'envelope, ce qui fait que à la recharge des parametres de clouds par défaut, on a une enveloppe avec des valeurs à 0 et des temps enormes, donc aucun son
- [x] la manipulation des fenetres de parametres de clouds demande quelques afinages, lorsqu'on se retrouve avec 6 ou 7 presentes, on ne sait plus laquelle on veut utiliser, et retaper "P" sur le cloud ne fait pas repasser celle lui correspondant au premier plan, on est donc obligé de fermer toutes les fenetres pour reafficher celle qui nous interesse, perte de temps et de souplesse enorme
- [x] lorsqu'on reaffiche la fenetre de parametres de clouds, elle ne se remet pas là ou on l'avait envoyéee à l'ecran, mais au milieu sur l'ecran ou se trouve la fenetre base (j'utilisais l'ecran du portable et un video projecteur comme deuxieme ecran)
- [x] certaines manipulations de parametres font disparaitre tout bonnement le son de maniere assez incompreensible. (que ce soit depuis la fenetre des parametres ou depuis celle des echantillons)
- [X] manipuler les parametres depuis la fenetre de dialogue s'est avéré bien plus pratique pour les enfants.
- [x] quelques situations amènent a voir les valeurs de certains parametres evoluer plus ou moins que ce qu'on avait demandé depuis la fenetre clouddialog
(apres tests poussés, il s'agit d'un bug du widget qdoublespinbow)
- [X] certains parametres affichés dans cloudDialog à sa crétion ne correspondent pas à ceux qu'on a dans la fenetre openGL
- [X] la sauvegarde de scene, et sa recharge changent les parametres d'envelopes
- [X] plantage a l'execution dans certaines circonstances apres avoir rechargé une scene enregistree, et que plusieurs fenetres de parametres sont affichées avant cette recharge. (il faudrait penser à detruire les fenetres de parametres quant on charge une scene)
- [x] si on ferme la fenetre principale sans avoir fermé un fenetre de parametres, le programme tourne toujours jusqu'a ce que l'on ferme la fenetre de parametres

je précise que j'ai travaillé avec ma version de developpement, un tout petit peu en avance sur le master actuel, integrant le pr que j'ai fait recemment, et une autre modif que je n'ai pas encore jointe reparant un bug sur l'ajout ou la supression de grains dans cloud.
les vus que j'ai rajoutés sont liés aux pr qui ont suivi.

**Comment by olof29** [comment]
(édité par @jpcima, voir post au dessus)

**Comment by jpcima** [comment]
Merci pour le retour.
J'ai mis en forme afin que cela puisse être suivi un peu plus facilement.
un peu HS moi ces derniers jours, j'ai un eu un peu du mal à suivre tout les changements.
