### ISSUE TITLE
polyphonie midi, probleme de comprehention dans la gestion des envelopes

### ISSUE THREAD

**Issue by olof29** [linuxmao-org/Frontieres#59]
j'ai implémenté la polyphonie midi dans la branche olofmidi de mon fork.
j'ai tout testé jusqu'à la production sonore dans nextbuffer.
et là il y a quelque chose qui a du m'echapper dans ma gestion des enveloppes, j'ai des envelopesaction qui se retrouvent à 0 , donc ni trigger, ni release, et ne peux donc pas prendre en compte les messages midi note off.

je passe par un tableau qui contient 32 CloudMidi avec chacun une note, un pitch, une velocité, une envelope, un buffer d'envelope (classe CloudMidi dans Cloud.cpp), que je gère au niveau de la fonction setActiveMidiState dans Cloud.cpp.
je precise que je n'ai pas encore traité la sauvegarde des banques et combinaisons midi, ni la question du pitch des notes, mais tout est en place pour le faire.
pour tester, il faut creer un cloud, creer une combinaison , l'affecter à un canal midi (menu midi), et mettre un clavier virtuel derriere sur le meme canal.

qu'ai je mal fait ?

**Comment by olof29** [comment]
bon, ai trouvé quelques erreurs, je sais maintenant gerer les envelopes en polyphonie.
ai par contre des bizarreries dans le son obtenu, meme une fois geres les pitchs.

si deux notes sont simultanées, il y a plein de craquements.

ma question reste d'actualité : 
- ma méthode est elle bonne ?

je ne pense pas, parceque je retrouve le probleme presenté au depart avec les envelopes, à savoir aussi un reste de la note précédente qui se lance à l'appuis sur une nouvelle note pour quelques instants avant de passer à la bonne, donc un buffer pas encore vidé ...

**Comment by olof29** [comment]
- j'ai l'intuition que les grains doivent aussi etre incorporés aux voix et que mes soucis sont dus au partage des grains du cloud par les différentes voix

**Comment by jpcima** [comment]
Tu veux bien ouvrir un PR en correspondance avec cette branche ?
c'est pour m'aider à étudier ton travail jusqu'ici.

**Comment by olof29** [comment]
c'est bon, je pense, ai resolu mes soucis. en effet il s'agissait d'un souci de partage des grains (plus quelques aneries maison...)
je mets un pr de cette fonctionnalité

**Comment by olof29** [comment]
je clos cette issue qui fait double emploi avec la #5 (pilotage midi) et y mets une reference vers ici pour garder une trace
