### ISSUE TITLE
[Feature Request] rendre l'interface Qt traduisible

### ISSUE THREAD

**Issue by trebmuh** [linuxmao-org/Frontieres#66]
Je viens de construire un paquet pour LZK2 à partir de https://github.com/linuxmao-org/Frontieres/commit/7c032e2820a790d86a3b7f5ebf45b0b4530fbf24 et je m'aperçois qu'une grande partie de l'interface est en anglais uniquement.

Ça serait bien de la rendre traduisible en français (et autres).

**Comment by jpcima** [comment]
Fait dans le commit adcf28350e84957fdc645617352a4197040d491f

**Comment by trebmuh** [comment]
Super, merci @jpcima 
J'ai fusionné un premier jet de traduction ici : https://github.com/linuxmao-org/Frontieres/commit/5c517d86c06db732e0c7d7e295737acfa19c0977

J'ai laissé "hanning" car je ne sais pas à quoi ça correspond. Le sais-tu ?

**Comment by jpcima** [comment]
"Hanning" est la contraction de Hann et de Hamming, les 2 auteurs qui ont donné le nom à cette formule.
