### ISSUE TITLE
[feature request] onglet de menu "à propos"

### ISSUE THREAD

**Issue by trebmuh** [linuxmao-org/Frontieres#67]
maintenant qu'il y a un menu, ça serait chouette d'avoir un onglet "à propos" traditionnel avec comme info :

- le fait que ce soit une reprise de borderlands (+ n° de version de borderlands au moment du fork) + le nom du dev de bordelands + un lien vers le site de borderlands
- les noms des développeurs et contributeurs de frontières
- un lien vers la forge (ici quoi)
- la licence utilisée

**Comment by jpcima** [comment]
Fait. 86446e784de6c5cc3cc84ce1660e2368b85506a5

**Comment by trebmuh** [comment]
Super !
J'ai fait une (tentative d') amélioration

**Comment by trebmuh** [comment]
Super !
J'ai fait une (tentative d') amélioration. Je te laisse fusionner si je ne me suis pas trompé @jpcima .
