### ISSUE TITLE
[feature request] auto-connexion des ports jack

### ISSUE THREAD

**Issue by trebmuh** [linuxmao-org/Frontieres#68]
Une option en ligne de commande pour qu'il s'auto-connecte aux sorties-système ça serait chouette.

**Comment by olof29** [comment]
si j'ai bien compris, cela rendrait impossible les 16 sorties, il serait alors obligatoire de n'avoir que le nombre de sorties de l'interface physique

**Comment by jpcima** [comment]
C'est implémenté à partir du commit a5473a04192c8ed0e84d83461d6ce0bef114c743.

On était précédemment face aux limitations de RtAudio, qui ne permet pas de flexibilité au niveau des connexions. J'ai implémenté l'API JACK directement.

L'option `-c` permet de choisir le nombre de canaux. C'est 16 par défaut.
L'option `-a` connecte les ports de JACK.

Un autre avantage de JACK en direct, c'est que l'audio et le MIDI sont traités avec un seul client, plutôt que 2. Ainsi c'est plus clair dans Qjackctl et Cadence.

**Comment by trebmuh** [comment]
Super, le `-a` fonctionne nickel. Merci.
