### ISSUE TITLE
[bogue] problème de crênelage

### ISSUE THREAD

**Issue by trebmuh** [linuxmao-org/Frontieres#69]
L'écran de départ possède une écriture crénelée (aliasing) :
![crenelage](https://user-images.githubusercontent.com/8705846/54483657-41837680-4857-11e9-8780-c971e2b94640.png)

**Comment by jpcima** [comment]
Devrait être résolu avec le commit a284158fb02ea75705da754a2e1467c3166d10df

**Comment by trebmuh** [comment]
Pas sûr :
![crenelage2](https://user-images.githubusercontent.com/8705846/54494071-d24d6700-48d6-11e9-819c-d7205c957e2f.png)

**Comment by jpcima** [comment]
Implémentation de la méthode MultiSampleAntiAnliasing, la manière de faire recommandée d'après ce que j'ai pu lire sur Khronos.
Ça devrait aller être raisonnablement rétrocompatible. À tester.

![Capture du 2019-03-17 20-53-07](https://user-images.githubusercontent.com/17614485/54497093-d8ebd680-48f6-11e9-8c03-60ac9e5d573b.png)
