### ISSUE TITLE
Format de traductions

### ISSUE THREAD

**Issue by jpcima** [linuxmao-org/Frontieres#7]
Puisque désormais le logiciel est bâti sur Qt, mieux vaut utiliser ses méthodes de traduction plutôt que Gettext.

Par ailleurs, je suspecte que désormais il soit possible d'écrire le texte accentué, à cause du changement du moteur de rendu de texte.À vérifier.

**Comment by trebmuh** [comment]
OK

> Par ailleurs, je suspecte que désormais il soit possible d'écrire le texte accentué, à cause du changement du moteur de rendu de texte.À vérifier.

Ça serait super !

_Pour info, je compte faire une construction pour LZK2 aujourd'hui pour tester tout ça._

**Comment by jpcima** [comment]
Ceci sera résolu par la PR #10 
On peut avoir désormais des caractères accentués. (ex appui sur Z pour "Tonalité")
Il faudra faire un `make install` préalable afin que les fichiers traductions soient à leur place. (à l'intérieur de PREFIX/share/Borderlands/translations)

Un programme `scripts/i18n.sh` permet de màj la source des traductions lorsque c'est nécessaire.

**Comment by trebmuh** [comment]
@jpcima c'est possible d'intégrer la construction des traductions dans le makefile ?

**Comment by jpcima** [comment]
La construction des qm est intégrée dans le cmake. (le `lrelease`)
Ce qui ne l'est pas, c'est de scanner les sources pour mettre à jour les ts. (le `lupdate`)

J'ai fait ça d'une manière un peu bricolée, puisque le projet ne contient pas de qmake.

**Comment by trebmuh** [comment]
ah ok, capiche !

**Comment by trebmuh** [comment]
Je viens de tester une construction à partir de la branche Qt, et la traduction FR fonctionne bien en français. Si je lance le logiciel avec un `LANG=C Borderlands`, le logiciel apparaît bien en anglais.

Bravo @jpcima !

Je ferme ici du coup.
