### ISSUE TITLE
[feature request] option de menu affichant tous les raccourcis clavier

### ISSUE THREAD

**Issue by trebmuh** [linuxmao-org/Frontieres#70]
Un genre de pense bête quoi.

**Comment by jpcima** [comment]
Fait. voir commit d06711d5d8aecfcdd894e664c16822cefc73b19f

**Comment by trebmuh** [comment]
Super !
Note qu'il n'y a pas le "N" (permettant d'afficher le nom de l'échantillon).
Je l'ajoute ?

**Comment by jpcima** [comment]
Je ne sais pas encore si je dois considérer celui-ci comme définitif, sachant que je vais sûrement revenir sur l'histoire de l'affichage des noms.

Il y a également le raccourci "M" que je songe à faire disparaître (sauvegarder la scène) ;
cette fonctionnalité est déjà disponible avec le traditionnel "Ctrl+S".

**Comment by trebmuh** [comment]
OK.
On ferme ici @jpcima où tu préfères le garder ouvert ?

**Comment by jpcima** [comment]
Ferme ici et également toutes les issues laissées ouvertes que tu considères terminées.
