### ISSUE TITLE
ne peux plus compiler dans qt

### ISSUE THREAD

**Issue by olof29** [linuxmao-org/Frontieres#74]
j'ai un message d'eereur maintenant à la compilation : 

`/home/olivier/developpement/Frontieres/libraries/QtFont3D/QtFont3D.h:13: erreur : QOpenGLFunctions: No such file or directory
 #include <QOpenGLFunctions>
                            ^`

une histoire de version de qt ?

**Comment by jpcima** [comment]
J'ai ajouté à l'instant la construction en Qmake à la CI, car je ne peux pas reproduire le problème de mon côté.
La construction se passe sur une Ubuntu 2014, avec Qt 5.5.1, plutôt ancien donc.
https://semaphoreci.com/jpcima/frontieres/branches/master/builds/110

La construction a fonctionné, à la suite de quelques modifs mineures sur le QMake.

As-tu esssayé de reconfigurer, ou bien nettoyer le dossier de construction ? (make clean/make distclean)

**Comment by jpcima** [comment]
Pour information `QOpenGLFunctions` fait partie du paquet `qtbase5-dev`.
Il se situe à l'emplacement : `/usr/include/x86_64-linux-gnu/qt5/QtGui/QOpenGLFunctions`

**Comment by olof29** [comment]
j'ai le paquet installé (depuis synaptic),
et ce fichier existe bien dans ce répertoire, mais j'ai ce message d'erreur quand meme

**Comment by olof29** [comment]
par contre, si je fais cmake et make, j'arrive a le compiler

**Comment by jpcima** [comment]
Je suis certain que c'est un problème de configuration de ton côté, avec Qmake.
Parfois c'est perturbé par un changement de version de Qt, et il faut tout réinitialiser pour que ça se remette en ordre.

(je note qu'il faut également que je mette à jour le .pro afin de gérer les options Jack/Pulse/Alsa)

**Comment by olof29** [comment]
tout reinitialiser, tu veux dire deisinstaller et reinstaller tout qt ?

**Comment by jpcima** [comment]
Non, je veux dire par là de refaire une construction sur un dossier de travail neuf, ne contenant aucun artefact provenant de compilations précédentes.

**Comment by olof29** [comment]
ça c'est le cas, j'ai meme supprimé le repetoire build

**Comment by olof29** [comment]
je suis completement perdu, hier encore j'ai pu compiler, et depuis la derniere version je n'ai rien changé sur mon systeme.
là j'ai tenté de desinstaller et reinstaller qt creator, le probleme reste le meme.

lorsque je veux explorer la liste des include possible et que je tape 
`#include <QOp`
je n'obtiens que 2 lignes QtOpenGL et QtOpenGL/ 
mais rien avec QOpenGL...

comment pourrais je voir les répertoires où qtcreator va chercher les includes possibles ?

**Comment by jpcima** [comment]
J'ai tenté d'ajouter ceci dans qmake.
https://github.com/linuxmao-org/Frontieres/commit/2698c2b093e7c78dbf3e3ac043a4ac34885c2d22

**Comment by olof29** [comment]
je l'ai testé a l'instant, ça ne change rien

**Comment by jpcima** [comment]
Ah, ca y est j'ai compris.
Tu es sur Qt4 ! et pas sur Qt5

**Comment by olof29** [comment]
je suis sur la version de debian proposée par synaptic sur ma librazik : 
5.7.1+dfsg-3+deb9u1

**Comment by olof29** [comment]
mais qtcreator est en 4.2, lui

**Comment by jpcima** [comment]
En CI j'installe un paquet [qt5-default](https://packages.debian.org/stretch/qt5-default)
Je crois qu'il faut dire au système lequel des deux versions de Qt est active, la 4 ou la 5.
En conséquence, la commande `qmake` renverra soit à `qmake-qt4`, ou bien `qmake-qt5`.

**Comment by olof29** [comment]
je viens de mettre ce paquet, ça ne change rien.
comment dire ça au syteme ?

**Comment by olof29** [comment]
et pourquoi donc ce probleme n'apparait il que maintenant ?

**Comment by olof29** [comment]
pour voir, je viens de lancer qmake en ligne de commande, et voici le contenu du .stash généré: 
`QMAKE_DEFAULT_INCDIRS = \

    /usr/include/c++/6 \

    /usr/include/x86_64-linux-gnu/c++/6 \

    /usr/include/c++/6/backward \

    /usr/lib/gcc/x86_64-linux-gnu/6/include \

    /usr/local/include \

    /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed \

    /usr/include/x86_64-linux-gnu \

    /usr/include

QMAKE_DEFAULT_LIBDIRS = \

    /usr/lib/gcc/x86_64-linux-gnu/6 \

    /usr/lib/x86_64-linux-gnu \

    /usr/lib \

    /lib/x86_64-linux-gnu \

    /lib`

**Comment by jpcima** [comment]
Je viens de me dire que le problème se trouve peut être à l'intérieur de Qt creator.

Je suis dans "Projet" > "Manage Kits"
![Capture du 2019-03-19 16-23-57](https://user-images.githubusercontent.com/17614485/54618571-8845bc00-4a63-11e9-957b-991ed18e1e76.png)

Peut-être faut il s'assurer que le "kit" actif renvoie bien à la version 5.12.

**Comment by olof29** [comment]
j'ai peut etre trouvé !

tu dois avoir raison sur la version

je viens de taper en ligne de commande  : 
`export QT_SELECT=5 `

et maintenant, dans la fenetre au lancement du projet, ou on peut le configurer, Qtcreator me propose 2 options  : 
- desktop
- Qt5.7.1 in path

si je choisi desktop, ou both, ça plante, si je ne choisis que Qt5.7.1 in path, ça fonctionne, je peux compiler.

j'ai donc ete dans manage kits et ai supprimé desktop des versions proposées par defaut

**Comment by olof29** [comment]
probleme resolu, merci beaucoup pour ton aide
