### ISSUE TITLE
décodage de format audio MP3

### ISSUE THREAD

**Issue by jpcima** [linuxmao-org/Frontieres#77]
On ne peut pas charger les fichiers de format MP3.
La bibliothèque sndfile ne gère pas le format.

Une solution consiste à intégrer [audio_decoder](https://github.com/x42/silan/tree/master/audio_decoder) de Robin Gareus, qui permet d'utiliser à la fois les décodeurs sndfile et ffmpeg.

**Comment by stilnat** [comment]
Je seconde, ce serait vraiment intéressant de pouvoir charger des MP3 !

**Comment by jpcima** [comment]
En effet, cela dit j'ai fait un essai rapide par ffmpeg, et audio_decoder a un problème de chargement avec la ffmpeg 4.1. Du coup j'ai remonté un bogue et je patiente un peu.

Si cela n'aboutit à rien, on codera un décodeur mp3 indépendant avec une des bibliothèques disponibles.

**Comment by jpcima** [comment]
Ajout du chargement de fichiers MPEG1/2/3 a1cdcdb

**Comment by stilnat** [comment]
@jpcima  je me suis embrouillé avec les commandes git j'ai fait un peu n'importe quoi, mais j'ai pu manuellement réintégrer ce que tu as fait pour les mp3 dans mon code source et la je voudrais uploader mon code source auquel j'ai ajouté la sauvegarde et le chargement des trajectoires ainsi que le choix circulaire mais j'ai des soucis git me dit qu'il y a des incompatibilités .. je sais pas trop quoi faire

**Comment by jpcima** [comment]
@stilnat si le commit à corriger est le dernier de la branche : tu peux remettre les fichiers originaux, et rectifier `git commit --amend`.

Si c'est enfoui plus loin dans l'historique, tu auras besoin de faire un rebase interactif pour remonter temporairement sur le commit que tu veux changer.

Dans les 2 cas, il faut après faire push avec le fanion `--force` ce qui permet la réécriture de l'historique.

C'est expliqué ici : https://git-scm.com/book/fr/v1/Utilitaires-Git-Réécrire-l-historique
