### ISSUE TITLE
créer une sortie audio stereo séparée par nuage en plus du master

### ISSUE THREAD

**Issue by olof29** [linuxmao-org/Frontieres#8]
dans le but de pouvoir appliquer des traitements separes sur chaque nuage, je voudrais creer une sortie audio stereo unique pour chaque nouveau nuage,  qui serait une copie conforme de ce que ce nuage envoit au master.
mes besoins : savoir comment creer ces sorties audio, ou les creer, et comment y assigner la production sonore du nuage

**Comment by jpcima** [comment]
>savoir comment creer ces sorties audio

Il y a moyen d'aboutir à ça mais y a des petites complications.
C'est surtout la bilbliothèque RtAudio sur laquelle le logiciel est bâtie. Je t'explique.
Cette biblio est un support générique de toutes les interfaces audio (Jack, aussi Alsa et les autres)
Elle a moins de capacités que Jack en propose.

1. tu peux pas créer des ports dynamiquement, contrairement à jack (je mets un nouveau cloud, paf 2 nouveau ports apparaissent)
2. il veut pas te laisser créer + de ports que ce dont dispose la carte son à laquelle tu connectes.

Voila comment tu peux faire. (sinon, faire directement du jack est une solution)

1. tu réserves dès le début un nombre de ports max dont tu te serviras (ex: 64 ports)
2. en jack, j'ai moi même soumis ce patch à RtAudio, qui permet d'avoir autant de sorties qu'on veut lorsqu'on utilise une sortie jack et qu'on utilise des connexions virtuelles.
Pour celà il faut modifier le programme pour construire le flux de RtAudio avec `RTAUDIO_JACK_DONT_CONNECT`

**Comment by jpcima** [comment]
Ensuite pour le mixage ça se passe ici. Tu peux voir que ça itère, sur tous les clouds et ça les écrit dans la sortie en stéréo entrelacé.
Faudra modifier ce code afin de pouvoir travailler en N-canaux, N > 2.

https://github.com/linuxmao-org/Borderlands/blob/a37549bb89f4c595261804b604da966b05a849e5/Borderlands.cpp#L241-L246

EDIT correction

**Comment by olof29** [comment]
je ne cherche pas vraiment à travailler en n canaux, mais à envoyer la meme chose sur les deux canaux principaux et sur deux canaux dediés à chaque cloud

**Comment by olof29** [comment]
et utiliser jack qui permet ça à la place de rtaudio ? ça serait faisable, il y aurait des inconvenients ?

**Comment by jpcima** [comment]
On peut utiliser jack à la place de rtAudio.
Avantage : c'est une bibliothèque facile à utiliser, un peu plus riche.
Inconvénient : ça ne sera pas compatible avec un usage normal d'utilisateur windows ou mac, ou même linuxien qui n'est pas un utilisateur de jack.
alors, ce serait le mieux d'avoir accès aux 2 choix, par exemple à l'aide d'une compilation conditionnelle.

avec jack tu auras une possibilité de créer un port dynamique lorsque tu fais un nouveau cloud (cf `jack_port_register`/`jack_port_unregister`)

**Comment by trebmuh** [comment]
> alors, ce serait le mieux d'avoir accès aux 2 choix, par exemple à l'aide d'une compilation conditionnelle.

Encore mieux, un fanion de démarrage en CLI, comme ça, on peut choisir soit l'un, soit l'autre à l'exécution et on est pas dépendant des mainteneurs de distributions/paquets qui seraient obligés de faire un choix Cornélien ici. :nerd_face:

**Comment by olof29** [comment]
mais pour que borderlands fonctionne sous linux, il faut imperativement que jack soit lancé, non ?

**Comment by olof29** [comment]
je reviens sur ce fil, pour discuter de nouveau du choix à faire ici.
je m'explique : 
- comme je l'ai dit plus haut, il me semble que de toute façon, il est impossible de faire tourner Frontieres actuellement sous linux sans lancer jack. je me trompe ? en tout cas chez moi, il plante avec un message no audio device found si je n'ai pas lancé jack...
- je ne sais pas du tout si sur d'autres os c'est le cas (je n'utilise que linux)
- si c'est bien le cas, alors il me semble que la question de savoir si on veut utiliser jack a la place de rtaudio me semble inutile, si de toute façon il faut jack, autant utiliser la bibliotheque la plus puissante.
- j'ai personnellement besoin, musicalement, dans un avenir tres proche d'utiliser Frontieres avec une sortie differente pour chaque cloud afin de traiter differemment ceux ci. pour le moment, via les fonctions de sauvegarde et recharge de scenes que j'ai ajoutées, j'arrive à realiser ce que je veux, mais cela m'oblige à lancer autant d'instances de Frontieres que j'ai de clouds, à recharger dans chaque instance ma scene, puis à y muter tous les clouds sauf un. ça fonctionne, mais c'est forcement gourmand en memoire vu le nombre d'instances que je vais etre amené à utiliser (20 au moins sur un projet que je vais monter d'ici un mois)
- donc j'envisage de me plonger dans l'utilisation des bibliotheques jack pour tenter de mettre en place ces sorties separees, mais je ne veux pas non plus lancer un truc qui ne serait pas la bonne solution.
- et si on mixait les deux possibilités, garder l'existant en rtaudio, et rajouter des ports via jack ?

**Comment by jpcima** [comment]
>il est impossible de faire tourner Frontieres actuellement sous linux sans lancer jack. je me trompe ?

Pas tout à fait. En RtAudio il faut activer une compilation conditionnelle des interfaces supplémentaires à l'aide d'un `define`.
Il est vrai que j'ai seulement activé jack dans le fichier de projet, tu peux ajouter les autres.
(par ailleurs c'est possible d'exprimer une condition en qmake sur l'os utilisé, de sorte à activer aussi windows et mac)

`Frontieres.pro`
```
DEFINES += __LINUX_ALSASEQ__ # MIDI ALSA
DEFINES += __UNIX_JACK__ # audio Jack
##DEFINES += __LINUX_ALSA__ # audio ALSA
##DEFINES += __LINUX_PULSE__ # audio Pulse
```

Je pourrai poser les bases d'une variante en jack, ça n'a rien de compliqué.
Mais de préférence pas avant de fusionner les quelques trucs en chantier actuellement, ce qui risquerait de déclencher des conflits à tout va.

**Comment by olof29** [comment]
il serait bon, de toute façon , de pouvoir choisir, à la maniere de hydrogen, par exemple, si on veut utiliser des sorties separees ou non, depuis l'interieur du logiciel.

**Comment by olof29** [comment]
il serait suffisant, je pense, d'ajouter un parametre canal audio aux clouds, et de creer 16 canaux audio stereo au lieu d'un, dans l'optique de l'utilisation midi.
cela permettrait  deja en utilisation midi de permettre d'envoyer chaque combinaison (canal midi) vers une sortie différente, et d'y appliquer à l'extérieur de Frontieres, les effets qui nous conviennent, d'enregistrer séparément...

(voir Pilotage MIDI #5)

si j'ai bien compris, cela ne serait pas trop compliqué ?

**Comment by olof29** [comment]
- j'ai rajouté la gestion de plusieurs sorties audio sans trop de soucis grace à tes conseils et à l'option RTAUDIO_JACK_DONT_CONNECT pour rtaudio.
- là j'ai mis un pr (ajout de la gestion de plusieurs sorties audio à la gestion du midi #64)
qui le propose en 16 sorties, mais ça fonctionne aussi bien pour plus de sorties, il suffit de changer la valeur de MY_CHANNELS dans theglobals.h
- il est envisageable de de paramétrer le nombre de sorties depuis les options de Frontieres et de le demander de relancer le programme pour en tenir compte.
- j'ai gardé les différentes logiques de balances existantes, en rajoutant 2 parametres aux clouds : premiere et derniere sortie (on les trouve dans la fenetre de parametres)

**Comment by olof29** [comment]
je pense qu'on peut considérer maintenant cette fonctionnalité comme implantée, depuis l'autoconnect et le choix du nombre de sorties passés en paramètres
