### ISSUE TITLE
organisation des sources

### ISSUE THREAD

**Issue by trebmuh** [linuxmao-org/Frontieres#9]
Suggestion d'organiser les sources du logiciel (*.cpp, *.h,...) dans un répertoire `src/`, histoire d'y voir un peu plus clair.

**Comment by jpcima** [comment]
Oui, on peut même faire mieux.

Par exemple l'auteur du logiciel dit que tu as des dichotomies du genre "GrainCloud", "GrainCloudVis" ; où "Vis" représente le visuel d'un élément logique particulier.
Ces éléments de code code sont organisés en méli-mélo, on pourrait faire la distinction en séparant éléments graphiques et logiques, ce qui saurait rendre le code un peu plus travaillable encore.

(de plus petites unités de code, moins de "surcharge cérébrale")

**Comment by jpcima** [comment]
Les unités de code sont désormais divisées en un ensemble un peu plus abordable, ordonné de sorte à inciter la séparation systèmatique entre modèle et vue, correspondant à un modèle à peu près ontologiquement correct, je l'espère.
C'est désirable pour la poursuite d'un développement un peu moins monolithique que ce que le logiciel a été jusque là. Par ailleurs cela me permettra de mettre en place la suite du plan permettant l'édition en temps réel.

**Comment by trebmuh** [comment]
@jpcima du coup on ferme ici ou tu penses qu'il y a encore des choses à faire ?

**Comment by jpcima** [comment]
Le travail est pour l'essentiel accompli, je ne pense pas que ce soit utile de garder cette issue ouverte.
